<div class="info">
	<h3>Conheça nossos serviços,</h3>
	<p>eles são legais!</p>
</div>
<div class="s-left">
	<div class="buttons">
		<button class="btn btn-sm">Websites</button>
		<button class="btn btn-sm">Sistemas</button>
		<button class="btn btn-sm">Posicionamento</button>
	</div>
	<?php include("assets/image/screen.svg"); ?>
</div>
<div class="s-right">
	<div class="s-title">
		<p>Lorem ipsum dolor sit amet, no ridens invidunt scripserit nec, choro eirmod duo eu. Ex nostro dolorem sit, eu nobis lucilius delicatissimi nam. Partem iuvaret conceptam eum id, sea mazim officiis imperdiet ne. Te enim accusamus deseruisse his, vim oratio repudiare iracundia ei. An per nostrum nominati, vix no dolore doming tractatos. Nulla saepe qualisque te sea, ut eum amet dolore apeirian</p>
	</div>
	<div class="s-content">
		<a class="btn btn-lg" href="#">+ informações</a>
	</div>
</div>